# .github/dependabot.yml
version: 2
updates:
  # npm / yarn の依存関係をチェック
  - package-ecosystem: npm
    directory: "/"               # package.json の場所
    schedule:
      interval: daily            # 毎日チェック
    open-pull-requests-limit: 10
    allow:
      - dependency-type: all     # dependencies, devDependencies, transitive 全部

  # GitHub Actions の依存関係も更新
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly