name: CI

on:
  push:
    branches:
      - main
      - dependabot/**   # Dependabot のブランチも対象
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのチェックアウト
      - uses: actions/checkout@v5

      # Node のセットアップ（.nvmrc に従う）
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: "yarn"

      # Yarn 依存関係インストール
      - run: yarn install --immutable

      # ビルド
      - run: yarn build

      # テスト（あれば）
      - run: yarn test || echo "テストなしでも続行"
